#!/bin/sh

. ./create_nginx.config
. ./functions-apache

VEDIR=/var/lib/vz/private/$VEID

# Apache2
VHOSTSDIR=$VEDIR/etc/httpd2/conf/sites-enabled

NGINXSITES=/etc/nginx/sites-enabled.d/azbyka.d

mkdir -p $NGINXSITES

get_var()
{
	grep -i "^ *$2 " "$1" | head -n 1 | sed -e "s/^[ \t]*$2[ \t]*//g" | sed -e 's/"//g'
}


print_nginx_conf()
{
cat <<EOF
# generated by $(realpath $0)

    location /$NAME {
        root $HOMEDIR/$SEPUSER/www/$SITE;

        # FIXME
        set \$subserver http://sites${SITEPORT/:/};

        # Тоже некоторая проблема: видимо, надо вставлять внутрь
        location ~* .*/wp-login.php$ {
                proxy_pass \$subserver;
                include include/trans-proxy.conf;
                access_log  /var/log/nginx/$SEPUSER-access.log logdetail;
                error_log  /var/log/nginx/$SEPUSER-error.log;
                #break;

        }

        # Вместо несуществующих jpg, png, gif отдаём приготовленную картинку
        include include/static-stub.conf;

        # пробуем отдать напрямую статикой, не получится - на @fallback
        # FIXME: fallback будет не туда, вернул /news, помогло
        # Но что делать потом? Рассчитываем на readonly доступ
        include include/static-fallback.conf;

        include include/stop-injection.conf;

        proxy_pass \$subserver;
        include include/trans-proxy.conf;
        access_log  /var/log/nginx/$SEPUSER-access.log logdetail;
        error_log  /var/log/nginx/$SEPUSER-error.log;
    }
EOF
}

#for i in $VHOSTSDIR/azbyka_*.conf ; do
for i in $VHOSTSDIR/azbyka_news.conf ; do
	parse_site_config $i
	SITE=$DOMAINNAME
	if [ ! -n "$SITE" ] ; then
		echo "Skipping $i..."
		continue
	fi
	DROOT=$(get_var $i DocumentRoot)
	#NAME=${SITE/azbyka_/}
	NAME=$(basename $i .conf)
	NAME=${NAME/azbyka_/}
	echo $NAME $SITE $DROOT
	SEPUSER="azbyka_$NAME"
	print_nginx_conf >$NGINXSITES/$NAME.conf
cat <<EOF >>/etc/nginx/httpconf-enabled.d/upstream_sites.conf

# for site $DOMAINNAME/$NAME
upstream sites${SITEPORT/:/} {
   server $APACHEHOST:${SITEPORT/:/};
   server $APACHEHOST2:${SITEPORT/:/} backup;
}
EOF

done
