#!/bin/sh

. ./create_nginx.config

VEDIR=/var/lib/vz/private/$VEID

# Apache2
VHOSTSDIR=$VEDIR/etc/httpd2/conf/sites-enabled

NGINXSITES=/etc/nginx/sites-enabled.d/azbyka.d

mkdir -p $NGINXSITES

get_var()
{
	grep -i "^ *$2 " "$1" | head -n 1 | sed -e "s/^[ \t]*$2[ \t]*//g" | sed -e 's/"//g'
}


print_nginx_conf()
{
cat <<EOF
# generated by $(realpath $0)

    location /$NAME/ {
        root $VEDIR/home/$SITE/www/$SITE;

        # Тоже некоторая проблема: видимо, надо вставлять внутрь
        location ~* .*/wp-login.php$ {
                proxy_pass \$subserver;
                #set \$host azbyka_news.site.azbyka.ru;
                proxy_set_header Host $SITE.site.azbyka.ru;
                include include/fulltrans-proxy.conf;
                access_log  /var/log/nginx/$SITE-access.log logdetail;
                error_log  /var/log/nginx/$SITE-error.log;
                #break;

        }

        # Вместо несуществующих jpg, png, gif отдаём приготовленную картинку
        include include/static-stub.conf;

        # пробуем отдать напрямую статикой, не получится - на @fallback
	# FIXME: fallback будет не туда, вернул /news, помогло
	# Но что делать потом? Рассчитываем на readonly доступ
        include include/static-fallback.conf;

        proxy_pass \$subserver;
        #set \$host azbyka_news.site.azbyka.ru;
        proxy_set_header Host $SITE.site.azbyka.ru;
        include include/fulltrans-proxy.conf;
        access_log  /var/log/nginx/$SITE-access.log logdetail;
        error_log  /var/log/nginx/$SITE-error.log;
    }
EOF
}

for i in $VHOSTSDIR/azbyka_*.conf ; do
	SITE=$(get_var $i ServerName)
	if [ ! -n "$SITE" ] ; then
		echo "Skipping $i..."
		continue
	fi
	DROOT=$(get_var $i DocumentRoot)
	NAME=${SITE/azbyka_/}
	echo $NAME $SITE $DROOT

	print_nginx_conf >$NGINXSITES/$NAME.conf
done
